// Generated by metal0 --emit-logic-table
// Import this file into LanceQL to use compiled @logic_table functions

const std = @import("std");

pub const VectorOps = struct {
    pub const __logic_table__ = true;

    pub const cosine_sim_deps = [_]struct { table: []const u8, column: []const u8 }{
        .{ .table = "query", .column = "embedding" },
        .{ .table = "docs", .column = "embedding" },
    };

    pub fn cosine_sim(query_embedding: []const f32, docs_embedding: []const f32, out: []f32) void {
        const len = out.len;
        var i: usize = 0;
        while (i < len) : (i += 1) {
            out[i] = (blk: { var __sum: f32 = 0.0; var __j: usize = 0; while (__j < query_embedding.len) : (__j += 1) { __sum += (query_embedding[i] * docs_embedding[i]); } break :blk __sum; } / (@sqrt(blk: { var __sum: f32 = 0.0; var __j: usize = 0; while (__j < query_embedding.len) : (__j += 1) { const __v = query_embedding[i]; __sum += __v * __v; } break :blk __sum; }) * @sqrt(blk: { var __sum: f32 = 0.0; var __j: usize = 0; while (__j < docs_embedding.len) : (__j += 1) { const __v = docs_embedding[i]; __sum += __v * __v; } break :blk __sum; })));
        }
    }

    pub const dot_product_deps = [_]struct { table: []const u8, column: []const u8 }{
        .{ .table = "query", .column = "embedding" },
        .{ .table = "docs", .column = "embedding" },
    };

    pub fn dot_product(query_embedding: []const f32, docs_embedding: []const f32, out: []f32) void {
        const len = out.len;
        var i: usize = 0;
        while (i < len) : (i += 1) {
            out[i] = blk: { var __sum: f32 = 0.0; var __j: usize = 0; while (__j < query_embedding.len) : (__j += 1) { __sum += (query_embedding[i] * docs_embedding[i]); } break :blk __sum; };
        }
    }

    pub const weighted_score_deps = [_]struct { table: []const u8, column: []const u8 }{
        .{ .table = "query", .column = "score" },
        .{ .table = "docs", .column = "boost" },
    };

    pub fn weighted_score(query_score: []const f32, docs_boost: []const f32, out: []f32) void {
        const len = out.len;
        var i: usize = 0;
        while (i < len) : (i += 1) {
            out[i] = ((query_score[i] * @as(f32, 0.5)) + (docs_boost[i] * @as(f32, 0.5)));
        }
    }

    pub const methods = [_][]const u8{
        "cosine_sim",
        "dot_product",
        "weighted_score",
    };
};

